// Code generated by protoc-gen-go.
// source: CommonData.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	CommonData.proto
	Game.proto
	Other.proto
	Protos.proto
	Room.proto

It has these top-level messages:
	UserData
	ChangeMsg
	PlayerInfo
	DeskInfo
	GMGameReq
	GMGameRes
	HeartBeat
	LoginReq
	LoginRes
	PlayerInfoUpdate
	BuyItems
	GetVipShopListReq
	GetVipShopListRes
	BuyItemReq
	BuyItemRes
	CreateDeskReq
	CreateDeskRes
	CheckInDeskReq
	CheckInDeskRes
	GameDataInfo
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserData struct {
	UserId   int32  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Gold     int32  `protobuf:"varint,4,opt,name=gold" json:"gold,omitempty"`
	Diamond  int32  `protobuf:"varint,5,opt,name=diamond" json:"diamond,omitempty"`
	Exp      int32  `protobuf:"varint,6,opt,name=exp" json:"exp,omitempty"`
	Mobile   string `protobuf:"bytes,7,opt,name=mobile" json:"mobile,omitempty"`
	Level    int32  `protobuf:"varint,8,opt,name=level" json:"level,omitempty"`
	VipLevel int32  `protobuf:"varint,9,opt,name=vipLevel" json:"vipLevel,omitempty"`
}

func (m *UserData) Reset()                    { *m = UserData{} }
func (m *UserData) String() string            { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()               {}
func (*UserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserData) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *UserData) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *UserData) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *UserData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserData) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserData) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

type ChangeMsg struct {
	IsLevelUp     bool `protobuf:"varint,1,opt,name=isLevelUp" json:"isLevelUp,omitempty"`
	IsVipLevelUp  bool `protobuf:"varint,2,opt,name=isVipLevelUp" json:"isVipLevelUp,omitempty"`
	IsHaveNewMail bool `protobuf:"varint,3,opt,name=isHaveNewMail" json:"isHaveNewMail,omitempty"`
}

func (m *ChangeMsg) Reset()                    { *m = ChangeMsg{} }
func (m *ChangeMsg) String() string            { return proto.CompactTextString(m) }
func (*ChangeMsg) ProtoMessage()               {}
func (*ChangeMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChangeMsg) GetIsLevelUp() bool {
	if m != nil {
		return m.IsLevelUp
	}
	return false
}

func (m *ChangeMsg) GetIsVipLevelUp() bool {
	if m != nil {
		return m.IsVipLevelUp
	}
	return false
}

func (m *ChangeMsg) GetIsHaveNewMail() bool {
	if m != nil {
		return m.IsHaveNewMail
	}
	return false
}

type PlayerInfo struct {
	UserId   int32  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Gold     int32  `protobuf:"varint,4,opt,name=gold" json:"gold,omitempty"`
	Level    int32  `protobuf:"varint,8,opt,name=level" json:"level,omitempty"`
	VipLevel int32  `protobuf:"varint,9,opt,name=vipLevel" json:"vipLevel,omitempty"`
}

func (m *PlayerInfo) Reset()                    { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()               {}
func (*PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PlayerInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *PlayerInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *PlayerInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *PlayerInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PlayerInfo) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

type DeskInfo struct {
	GameType     int32         `protobuf:"varint,1,opt,name=gameType" json:"gameType,omitempty"`
	GameName     string        `protobuf:"bytes,2,opt,name=gameName" json:"gameName,omitempty"`
	MaxPlayerCnt int32         `protobuf:"varint,3,opt,name=maxPlayerCnt" json:"maxPlayerCnt,omitempty"`
	MinPlayerCnt int32         `protobuf:"varint,4,opt,name=minPlayerCnt" json:"minPlayerCnt,omitempty"`
	PlayerData   []*PlayerInfo `protobuf:"bytes,5,rep,name=playerData" json:"playerData,omitempty"`
}

func (m *DeskInfo) Reset()                    { *m = DeskInfo{} }
func (m *DeskInfo) String() string            { return proto.CompactTextString(m) }
func (*DeskInfo) ProtoMessage()               {}
func (*DeskInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeskInfo) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *DeskInfo) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *DeskInfo) GetMaxPlayerCnt() int32 {
	if m != nil {
		return m.MaxPlayerCnt
	}
	return 0
}

func (m *DeskInfo) GetMinPlayerCnt() int32 {
	if m != nil {
		return m.MinPlayerCnt
	}
	return 0
}

func (m *DeskInfo) GetPlayerData() []*PlayerInfo {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

func init() {
	proto.RegisterType((*UserData)(nil), "msg.UserData")
	proto.RegisterType((*ChangeMsg)(nil), "msg.ChangeMsg")
	proto.RegisterType((*PlayerInfo)(nil), "msg.PlayerInfo")
	proto.RegisterType((*DeskInfo)(nil), "msg.DeskInfo")
}

func init() { proto.RegisterFile("CommonData.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x52, 0x4b, 0x4e, 0xc3, 0x30,
	0x10, 0x55, 0x9a, 0xa6, 0x4d, 0x06, 0x10, 0xd5, 0x08, 0x21, 0x0b, 0xb1, 0x40, 0x11, 0x8b, 0xae,
	0x8a, 0x04, 0x47, 0x68, 0x17, 0x20, 0xd1, 0x0a, 0x45, 0x94, 0xbd, 0xab, 0x98, 0x60, 0x91, 0xc4,
	0x56, 0x5d, 0x42, 0x7b, 0x19, 0x2e, 0xc2, 0x65, 0x38, 0x0a, 0xf6, 0x24, 0xfd, 0x64, 0xc9, 0x82,
	0xdd, 0xbc, 0x37, 0xcf, 0x93, 0x37, 0x2f, 0x03, 0x83, 0xb1, 0x2a, 0x0a, 0x55, 0x4e, 0xf8, 0x8a,
	0x8f, 0xf4, 0x52, 0xad, 0x14, 0xfa, 0x85, 0xc9, 0xe2, 0x1f, 0x0f, 0xc2, 0xb9, 0x11, 0x4b, 0xc7,
	0xe3, 0x39, 0xf4, 0x3e, 0x6c, 0xfd, 0x90, 0x32, 0xef, 0xca, 0x1b, 0x06, 0x49, 0x83, 0xf0, 0x02,
	0x42, 0x57, 0xcd, 0x78, 0x21, 0x58, 0xc7, 0x76, 0xa2, 0x64, 0x87, 0xdd, 0x1b, 0x5e, 0xd9, 0xc7,
	0x4b, 0xe6, 0x53, 0xa7, 0x41, 0x88, 0xd0, 0xcd, 0x54, 0x9e, 0xb2, 0x2e, 0x4d, 0xa2, 0x1a, 0x19,
	0xf4, 0x53, 0xc9, 0xad, 0x8b, 0x94, 0x05, 0x44, 0x6f, 0x21, 0x0e, 0xc0, 0x17, 0x6b, 0xcd, 0x7a,
	0xc4, 0xba, 0xd2, 0xcd, 0x2d, 0xd4, 0x42, 0xe6, 0x82, 0xf5, 0xeb, 0xb9, 0x35, 0xc2, 0x33, 0x08,
	0x72, 0x51, 0x89, 0x9c, 0x85, 0xa4, 0xad, 0x81, 0x73, 0x58, 0x49, 0xfd, 0x48, 0x8d, 0x88, 0x1a,
	0x3b, 0x1c, 0x1b, 0x88, 0xc6, 0x6f, 0xbc, 0xcc, 0xc4, 0xd4, 0x64, 0x78, 0x09, 0x91, 0x34, 0xc4,
	0xcf, 0x35, 0x6d, 0x19, 0x26, 0x7b, 0x02, 0x63, 0x38, 0x96, 0xe6, 0xa5, 0x79, 0x68, 0x05, 0x1d,
	0x12, 0xb4, 0x38, 0xbc, 0x86, 0x13, 0x69, 0xee, 0x79, 0x25, 0x66, 0xe2, 0x73, 0xca, 0x65, 0x4e,
	0x7b, 0x87, 0x49, 0x9b, 0x8c, 0xbf, 0x3c, 0x80, 0xa7, 0x9c, 0x6f, 0x6c, 0x7e, 0xe5, 0xab, 0xfa,
	0xf7, 0x64, 0xff, 0x9e, 0xca, 0xb7, 0xfd, 0xf1, 0x13, 0x61, 0xde, 0xc9, 0x9e, 0x15, 0x66, 0xf6,
	0x93, 0xcf, 0x1b, 0x2d, 0x1a, 0x83, 0x3b, 0xbc, 0xed, 0x1d, 0x5a, 0xdc, 0x62, 0x97, 0x57, 0xc1,
	0xd7, 0xf5, 0x9e, 0xe3, 0x72, 0x45, 0x46, 0x83, 0xa4, 0xc5, 0x91, 0x46, 0x96, 0x7b, 0x4d, 0xb7,
	0xd1, 0x1c, 0x70, 0x78, 0x03, 0xa0, 0x09, 0xb8, 0x33, 0xb4, 0xb7, 0xe1, 0x0f, 0x8f, 0x6e, 0x4f,
	0x47, 0xf6, 0x3e, 0x47, 0xfb, 0x0c, 0x93, 0x03, 0xc9, 0xa2, 0x47, 0x27, 0x7c, 0xf7, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x74, 0xf7, 0x4b, 0xc2, 0xd6, 0x02, 0x00, 0x00,
}
