// Code generated by protoc-gen-go.
// source: CommonData.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	CommonData.proto
	Game.proto
	Other.proto
	Protos.proto

It has these top-level messages:
	UserData
	ChangeMsg
	PlayTableData
	PattenData
	ResultData
	OneArmPlayReq
	OneArmPlayRes
	CenterItems
	HitItems
	SingleTurn
	OneRound
	MarryGameInfos
	GMGameReq
	GMGameRes
	HeartBeat
	LoginReq
	LoginRes
	PlayerInfoUpdate
	BuyItems
	GetVipShopListReq
	GetVipShopListRes
	BuyItemReq
	BuyItemRes
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserData struct {
	UserId   int32  `protobuf:"varint,1,opt,name=userId" json:"userId,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=userName" json:"userName,omitempty"`
	Avatar   string `protobuf:"bytes,3,opt,name=avatar" json:"avatar,omitempty"`
	Gold     int32  `protobuf:"varint,4,opt,name=gold" json:"gold,omitempty"`
	Diamond  int32  `protobuf:"varint,5,opt,name=diamond" json:"diamond,omitempty"`
	Exp      int32  `protobuf:"varint,6,opt,name=exp" json:"exp,omitempty"`
	Mobile   string `protobuf:"bytes,7,opt,name=mobile" json:"mobile,omitempty"`
	Level    int32  `protobuf:"varint,8,opt,name=level" json:"level,omitempty"`
	VipLevel int32  `protobuf:"varint,9,opt,name=vipLevel" json:"vipLevel,omitempty"`
}

func (m *UserData) Reset()                    { *m = UserData{} }
func (m *UserData) String() string            { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()               {}
func (*UserData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserData) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserData) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserData) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *UserData) GetDiamond() int32 {
	if m != nil {
		return m.Diamond
	}
	return 0
}

func (m *UserData) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *UserData) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserData) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserData) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

type ChangeMsg struct {
	IsLevelUp     bool `protobuf:"varint,1,opt,name=isLevelUp" json:"isLevelUp,omitempty"`
	IsVipLevelUp  bool `protobuf:"varint,2,opt,name=isVipLevelUp" json:"isVipLevelUp,omitempty"`
	IsHaveNewMail bool `protobuf:"varint,3,opt,name=isHaveNewMail" json:"isHaveNewMail,omitempty"`
}

func (m *ChangeMsg) Reset()                    { *m = ChangeMsg{} }
func (m *ChangeMsg) String() string            { return proto.CompactTextString(m) }
func (*ChangeMsg) ProtoMessage()               {}
func (*ChangeMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChangeMsg) GetIsLevelUp() bool {
	if m != nil {
		return m.IsLevelUp
	}
	return false
}

func (m *ChangeMsg) GetIsVipLevelUp() bool {
	if m != nil {
		return m.IsVipLevelUp
	}
	return false
}

func (m *ChangeMsg) GetIsHaveNewMail() bool {
	if m != nil {
		return m.IsHaveNewMail
	}
	return false
}

func init() {
	proto.RegisterType((*UserData)(nil), "msg.UserData")
	proto.RegisterType((*ChangeMsg)(nil), "msg.ChangeMsg")
}

func init() { proto.RegisterFile("CommonData.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x69, 0xd3, 0xa4, 0x9b, 0x41, 0xa1, 0x0c, 0x22, 0x83, 0x78, 0x90, 0xe0, 0xc1, 0x93,
	0x17, 0x1f, 0xa1, 0x1e, 0x14, 0x6c, 0x0f, 0x81, 0x7a, 0xdf, 0x92, 0x21, 0x2e, 0xec, 0x76, 0x43,
	0xb6, 0x46, 0x1f, 0xd7, 0x47, 0x71, 0x77, 0x12, 0x2b, 0xbd, 0xcd, 0xf7, 0xfd, 0x33, 0xc3, 0xce,
	0xc2, 0x6a, 0xed, 0x9d, 0xf3, 0x87, 0x67, 0x7d, 0xd4, 0x8f, 0x5d, 0xef, 0x8f, 0x1e, 0x33, 0x17,
	0xda, 0xea, 0x67, 0x06, 0x6a, 0x17, 0xb8, 0x4f, 0x1e, 0xaf, 0xa1, 0xf8, 0x8c, 0xf5, 0x6b, 0x43,
	0xb3, 0xbb, 0xd9, 0x43, 0x5e, 0x4f, 0x84, 0x37, 0xa0, 0x52, 0xb5, 0xd5, 0x8e, 0x69, 0x1e, 0x93,
	0xb2, 0x3e, 0x71, 0x9a, 0xd1, 0x43, 0x1c, 0xee, 0x29, 0x93, 0x64, 0x22, 0x44, 0x58, 0xb4, 0xde,
	0x36, 0xb4, 0x90, 0x4d, 0x52, 0x23, 0xc1, 0xb2, 0x31, 0x3a, 0xbe, 0xa2, 0xa1, 0x5c, 0xf4, 0x1f,
	0xe2, 0x0a, 0x32, 0xfe, 0xee, 0xa8, 0x10, 0x9b, 0xca, 0xb4, 0xd7, 0xf9, 0xbd, 0xb1, 0x4c, 0xcb,
	0x71, 0xef, 0x48, 0x78, 0x05, 0xb9, 0xe5, 0x81, 0x2d, 0x29, 0xe9, 0x1d, 0x21, 0xbd, 0x70, 0x30,
	0xdd, 0x9b, 0x04, 0xa5, 0x04, 0x27, 0xae, 0x02, 0x94, 0xeb, 0x0f, 0x7d, 0x68, 0x79, 0x13, 0x5a,
	0xbc, 0x85, 0xd2, 0x04, 0xf1, 0xbb, 0x4e, 0xae, 0x54, 0xf5, 0xbf, 0xc0, 0x0a, 0x2e, 0x4c, 0x78,
	0x9f, 0x06, 0x63, 0xc3, 0x5c, 0x1a, 0xce, 0x1c, 0xde, 0xc3, 0xa5, 0x09, 0x2f, 0x7a, 0xe0, 0x2d,
	0x7f, 0x6d, 0xb4, 0xb1, 0x72, 0xb7, 0xaa, 0xcf, 0xe5, 0xbe, 0x90, 0x3f, 0x7e, 0xfa, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xff, 0xe8, 0x91, 0x2b, 0x77, 0x01, 0x00, 0x00,
}
