// Code generated by protoc-gen-go.
// source: Game.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GMGameReq struct {
	GmCmd string `protobuf:"bytes,1,opt,name=gmCmd" json:"gmCmd,omitempty"`
}

func (m *GMGameReq) Reset()                    { *m = GMGameReq{} }
func (m *GMGameReq) String() string            { return proto.CompactTextString(m) }
func (*GMGameReq) ProtoMessage()               {}
func (*GMGameReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GMGameReq) GetGmCmd() string {
	if m != nil {
		return m.GmCmd
	}
	return ""
}

type GMGameRes struct {
}

func (m *GMGameRes) Reset()                    { *m = GMGameRes{} }
func (m *GMGameRes) String() string            { return proto.CompactTextString(m) }
func (*GMGameRes) ProtoMessage()               {}
func (*GMGameRes) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func init() {
	proto.RegisterType((*GMGameReq)(nil), "msg.GMGameReq")
	proto.RegisterType((*GMGameRes)(nil), "msg.GMGameRes")
}

func init() { proto.RegisterFile("Game.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x72, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0x52, 0xe4, 0xe2, 0x74,
	0xf7, 0x05, 0x09, 0x06, 0xa5, 0x16, 0x0a, 0x89, 0x70, 0xb1, 0xa6, 0xe7, 0x3a, 0xe7, 0xa6, 0x48,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x4a, 0xdc, 0x08, 0x25, 0xc5, 0x49, 0x6c, 0x60,
	0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x49, 0x4e, 0x9b, 0xec, 0x49, 0x00, 0x00, 0x00,
}
