// Code generated by protoc-gen-go.
// source: Other.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ////////////////////心跳包/////////////////////////
type HeartBeat struct {
}

func (m *HeartBeat) Reset()                    { *m = HeartBeat{} }
func (m *HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()               {}
func (*HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

// /////////////////////登陆请求//////////////////////
type LoginReq struct {
	UserName       string `protobuf:"bytes,1,opt,name=userName" json:"userName,omitempty"`
	PassWd         string `protobuf:"bytes,2,opt,name=passWd" json:"passWd,omitempty"`
	LoginType      int32  `protobuf:"varint,3,opt,name=loginType" json:"loginType,omitempty"`
	AccessToken    string `protobuf:"bytes,4,opt,name=accessToken" json:"accessToken,omitempty"`
	ReconnectToken string `protobuf:"bytes,5,opt,name=reconnectToken" json:"reconnectToken,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *LoginReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginReq) GetPassWd() string {
	if m != nil {
		return m.PassWd
	}
	return ""
}

func (m *LoginReq) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LoginReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *LoginReq) GetReconnectToken() string {
	if m != nil {
		return m.ReconnectToken
	}
	return ""
}

type LoginRes struct {
	ReconnectToken string `protobuf:"bytes,1,opt,name=reconnectToken" json:"reconnectToken,omitempty"`
}

func (m *LoginRes) Reset()                    { *m = LoginRes{} }
func (m *LoginRes) String() string            { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()               {}
func (*LoginRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *LoginRes) GetReconnectToken() string {
	if m != nil {
		return m.ReconnectToken
	}
	return ""
}

// ////////////////用户数据更新通知///////////////////////
type PlayerInfoUpdate struct {
	UserInfo  *UserData  `protobuf:"bytes,1,opt,name=userInfo" json:"userInfo,omitempty"`
	ChangeMsg *ChangeMsg `protobuf:"bytes,2,opt,name=changeMsg" json:"changeMsg,omitempty"`
}

func (m *PlayerInfoUpdate) Reset()                    { *m = PlayerInfoUpdate{} }
func (m *PlayerInfoUpdate) String() string            { return proto.CompactTextString(m) }
func (*PlayerInfoUpdate) ProtoMessage()               {}
func (*PlayerInfoUpdate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *PlayerInfoUpdate) GetUserInfo() *UserData {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *PlayerInfoUpdate) GetChangeMsg() *ChangeMsg {
	if m != nil {
		return m.ChangeMsg
	}
	return nil
}

// ////////////////////现金商店列表//////////////////////
type BuyItems struct {
	ItemId        int64 `protobuf:"varint,1,opt,name=itemId" json:"itemId,omitempty"`
	Golds         int64 `protobuf:"varint,2,opt,name=golds" json:"golds,omitempty"`
	Money         int32 `protobuf:"varint,3,opt,name=money" json:"money,omitempty"`
	IsBestValue   bool  `protobuf:"varint,4,opt,name=isBestValue" json:"isBestValue,omitempty"`
	IsMostPopular bool  `protobuf:"varint,5,opt,name=isMostPopular" json:"isMostPopular,omitempty"`
}

func (m *BuyItems) Reset()                    { *m = BuyItems{} }
func (m *BuyItems) String() string            { return proto.CompactTextString(m) }
func (*BuyItems) ProtoMessage()               {}
func (*BuyItems) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *BuyItems) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *BuyItems) GetGolds() int64 {
	if m != nil {
		return m.Golds
	}
	return 0
}

func (m *BuyItems) GetMoney() int32 {
	if m != nil {
		return m.Money
	}
	return 0
}

func (m *BuyItems) GetIsBestValue() bool {
	if m != nil {
		return m.IsBestValue
	}
	return false
}

func (m *BuyItems) GetIsMostPopular() bool {
	if m != nil {
		return m.IsMostPopular
	}
	return false
}

type GetVipShopListReq struct {
}

func (m *GetVipShopListReq) Reset()                    { *m = GetVipShopListReq{} }
func (m *GetVipShopListReq) String() string            { return proto.CompactTextString(m) }
func (*GetVipShopListReq) ProtoMessage()               {}
func (*GetVipShopListReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

type GetVipShopListRes struct {
	ItemList []*BuyItems `protobuf:"bytes,1,rep,name=ItemList,json=itemList" json:"ItemList,omitempty"`
}

func (m *GetVipShopListRes) Reset()                    { *m = GetVipShopListRes{} }
func (m *GetVipShopListRes) String() string            { return proto.CompactTextString(m) }
func (*GetVipShopListRes) ProtoMessage()               {}
func (*GetVipShopListRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GetVipShopListRes) GetItemList() []*BuyItems {
	if m != nil {
		return m.ItemList
	}
	return nil
}

// /////////////////购买物品///////////////////////
type BuyItemReq struct {
	BuyItemId int64 `protobuf:"varint,1,opt,name=buyItemId" json:"buyItemId,omitempty"`
}

func (m *BuyItemReq) Reset()                    { *m = BuyItemReq{} }
func (m *BuyItemReq) String() string            { return proto.CompactTextString(m) }
func (*BuyItemReq) ProtoMessage()               {}
func (*BuyItemReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *BuyItemReq) GetBuyItemId() int64 {
	if m != nil {
		return m.BuyItemId
	}
	return 0
}

type BuyItemRes struct {
}

func (m *BuyItemRes) Reset()                    { *m = BuyItemRes{} }
func (m *BuyItemRes) String() string            { return proto.CompactTextString(m) }
func (*BuyItemRes) ProtoMessage()               {}
func (*BuyItemRes) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func init() {
	proto.RegisterType((*HeartBeat)(nil), "msg.HeartBeat")
	proto.RegisterType((*LoginReq)(nil), "msg.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "msg.LoginRes")
	proto.RegisterType((*PlayerInfoUpdate)(nil), "msg.PlayerInfoUpdate")
	proto.RegisterType((*BuyItems)(nil), "msg.BuyItems")
	proto.RegisterType((*GetVipShopListReq)(nil), "msg.GetVipShopListReq")
	proto.RegisterType((*GetVipShopListRes)(nil), "msg.GetVipShopListRes")
	proto.RegisterType((*BuyItemReq)(nil), "msg.BuyItemReq")
	proto.RegisterType((*BuyItemRes)(nil), "msg.BuyItemRes")
}

func init() { proto.RegisterFile("Other.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0x41, 0xcf, 0xd2, 0x40,
	0x10, 0x86, 0x53, 0x2b, 0x5f, 0xda, 0xad, 0x1f, 0xc1, 0xd5, 0x98, 0x86, 0x78, 0x20, 0x1b, 0x63,
	0xd4, 0x18, 0x0e, 0x78, 0xf7, 0x00, 0x26, 0x4a, 0x02, 0x4a, 0x56, 0xc0, 0xf3, 0xd2, 0x8e, 0xa5,
	0xa1, 0xed, 0xd6, 0xce, 0xf6, 0xd0, 0x3f, 0xe2, 0x4f, 0xf0, 0x77, 0xba, 0xbb, 0x2d, 0x05, 0xfd,
	0xb8, 0xf1, 0x3e, 0x33, 0x2f, 0x9d, 0x79, 0x77, 0x48, 0xf0, 0x4d, 0x1d, 0xa1, 0x9a, 0x96, 0x95,
	0x54, 0x92, 0xba, 0x39, 0x26, 0xe3, 0xd1, 0x42, 0xe6, 0xb9, 0x2c, 0x3e, 0x09, 0x25, 0x5a, 0xcc,
	0x02, 0xe2, 0x7f, 0x01, 0x51, 0xa9, 0x39, 0x08, 0xc5, 0xfe, 0x38, 0xc4, 0x5b, 0xc9, 0x24, 0x2d,
	0x38, 0xfc, 0xa2, 0x63, 0xe2, 0xd5, 0x08, 0xd5, 0x57, 0x91, 0x43, 0xe8, 0x4c, 0x9c, 0x37, 0x3e,
	0xef, 0x35, 0x7d, 0x41, 0xee, 0x4a, 0x81, 0xf8, 0x23, 0x0e, 0x1f, 0xd9, 0x4a, 0xa7, 0xe8, 0x4b,
	0xe2, 0x67, 0xc6, 0xbf, 0x6d, 0x4a, 0x08, 0x5d, 0x5d, 0x1a, 0xf0, 0x0b, 0xa0, 0x13, 0x12, 0x88,
	0x28, 0x02, 0xc4, 0xad, 0x3c, 0x41, 0x11, 0x3e, 0xb6, 0xd6, 0x6b, 0x44, 0x5f, 0x93, 0x61, 0x05,
	0x91, 0x2c, 0x0a, 0x88, 0x54, 0xdb, 0x34, 0xb0, 0x4d, 0xff, 0x51, 0x36, 0xeb, 0xe7, 0xc4, 0x1b,
	0x1e, 0xe7, 0xa6, 0xe7, 0x44, 0x46, 0x9b, 0x4c, 0x34, 0x50, 0x2d, 0x8b, 0x9f, 0x72, 0x57, 0xc6,
	0x42, 0x01, 0x7d, 0xdb, 0xee, 0x68, 0x88, 0x75, 0x05, 0xb3, 0xfb, 0xa9, 0xce, 0x69, 0xba, 0xd3,
	0xd0, 0x84, 0xc4, 0xfb, 0x32, 0x7d, 0x4f, 0xfc, 0xe8, 0x28, 0x8a, 0x04, 0xd6, 0x98, 0xd8, 0xad,
	0x83, 0xd9, 0xd0, 0xf6, 0x2e, 0xce, 0x94, 0x5f, 0x1a, 0xd8, 0x6f, 0x9d, 0xe4, 0xbc, 0x6e, 0x96,
	0x0a, 0x72, 0x34, 0x69, 0xa5, 0xfa, 0xc7, 0x32, 0xb6, 0xdf, 0x70, 0x79, 0xa7, 0xe8, 0x73, 0x32,
	0x48, 0x64, 0x16, 0xa3, 0xfd, 0x3b, 0x97, 0xb7, 0xc2, 0x50, 0xfd, 0x44, 0xd0, 0x74, 0xf9, 0xb5,
	0xc2, 0x64, 0x97, 0xe2, 0x1c, 0x50, 0xed, 0x45, 0x56, 0x83, 0xcd, 0xce, 0xe3, 0xd7, 0x88, 0xbe,
	0x22, 0xf7, 0x29, 0xae, 0x25, 0xaa, 0x8d, 0x2c, 0xeb, 0x4c, 0x54, 0x36, 0x3a, 0x8f, 0xff, 0x0b,
	0xd9, 0x33, 0xf2, 0xf4, 0x33, 0xa8, 0x7d, 0x5a, 0x7e, 0x3f, 0xca, 0x72, 0x95, 0xa2, 0xd2, 0x4f,
	0xcd, 0x3e, 0x3e, 0x84, 0x68, 0xb2, 0x31, 0xe3, 0x1b, 0xa9, 0xe7, 0x76, 0xfb, 0x6c, 0xce, 0x6b,
	0x71, 0x2f, 0xed, 0xca, 0xec, 0x1d, 0x21, 0x1d, 0x35, 0x87, 0xa3, 0x8f, 0xe0, 0xd0, 0xaa, 0x7e,
	0xe3, 0x0b, 0x60, 0x4f, 0xae, 0x7a, 0xf1, 0x70, 0x67, 0xaf, 0xf0, 0xc3, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5f, 0xab, 0xdb, 0xca, 0xab, 0x02, 0x00, 0x00,
}
