// Code generated by protoc-gen-go.
// source: Room.proto
// DO NOT EDIT!

package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateDeskReq struct {
	GameType int32 `protobuf:"varint,1,opt,name=gameType" json:"gameType,omitempty"`
}

func (m *CreateDeskReq) Reset()                    { *m = CreateDeskReq{} }
func (m *CreateDeskReq) String() string            { return proto.CompactTextString(m) }
func (*CreateDeskReq) ProtoMessage()               {}
func (*CreateDeskReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *CreateDeskReq) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

type CreateDeskRes struct {
	GameNum string `protobuf:"bytes,1,opt,name=gameNum" json:"gameNum,omitempty"`
}

func (m *CreateDeskRes) Reset()                    { *m = CreateDeskRes{} }
func (m *CreateDeskRes) String() string            { return proto.CompactTextString(m) }
func (*CreateDeskRes) ProtoMessage()               {}
func (*CreateDeskRes) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CreateDeskRes) GetGameNum() string {
	if m != nil {
		return m.GameNum
	}
	return ""
}

type CheckInDeskReq struct {
	GameNum string `protobuf:"bytes,1,opt,name=gameNum" json:"gameNum,omitempty"`
}

func (m *CheckInDeskReq) Reset()                    { *m = CheckInDeskReq{} }
func (m *CheckInDeskReq) String() string            { return proto.CompactTextString(m) }
func (*CheckInDeskReq) ProtoMessage()               {}
func (*CheckInDeskReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *CheckInDeskReq) GetGameNum() string {
	if m != nil {
		return m.GameNum
	}
	return ""
}

type CheckInDeskRes struct {
	DeskInfo *DeskInfo `protobuf:"bytes,1,opt,name=deskInfo" json:"deskInfo,omitempty"`
}

func (m *CheckInDeskRes) Reset()                    { *m = CheckInDeskRes{} }
func (m *CheckInDeskRes) String() string            { return proto.CompactTextString(m) }
func (*CheckInDeskRes) ProtoMessage()               {}
func (*CheckInDeskRes) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *CheckInDeskRes) GetDeskInfo() *DeskInfo {
	if m != nil {
		return m.DeskInfo
	}
	return nil
}

type GameDataInfo struct {
}

func (m *GameDataInfo) Reset()                    { *m = GameDataInfo{} }
func (m *GameDataInfo) String() string            { return proto.CompactTextString(m) }
func (*GameDataInfo) ProtoMessage()               {}
func (*GameDataInfo) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func init() {
	proto.RegisterType((*CreateDeskReq)(nil), "msg.CreateDeskReq")
	proto.RegisterType((*CreateDeskRes)(nil), "msg.CreateDeskRes")
	proto.RegisterType((*CheckInDeskReq)(nil), "msg.CheckInDeskReq")
	proto.RegisterType((*CheckInDeskRes)(nil), "msg.CheckInDeskRes")
	proto.RegisterType((*GameDataInfo)(nil), "msg.GameDataInfo")
}

func init() { proto.RegisterFile("Room.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x0a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x97, 0x12, 0x70, 0xce, 0xcf,
	0xcd, 0xcd, 0xcf, 0x73, 0x49, 0x2c, 0x49, 0x84, 0x08, 0x2b, 0x69, 0x73, 0xf1, 0x3a, 0x17, 0xa5,
	0x26, 0x96, 0xa4, 0xba, 0xa4, 0x16, 0x67, 0x07, 0xa5, 0x16, 0x0a, 0x49, 0x71, 0x71, 0xa4, 0x27,
	0xe6, 0xa6, 0x86, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0xc1, 0xf9, 0x4a,
	0x9a, 0xa8, 0x8a, 0x8b, 0x85, 0x24, 0xb8, 0xd8, 0x41, 0x92, 0x7e, 0xa5, 0xb9, 0x60, 0xb5, 0x9c,
	0x41, 0x30, 0xae, 0x92, 0x16, 0x17, 0x9f, 0x73, 0x46, 0x6a, 0x72, 0xb6, 0x67, 0x1e, 0xcc, 0x60,
	0xdc, 0x6a, 0xad, 0xd1, 0xd4, 0x16, 0x0b, 0x69, 0x72, 0x71, 0xa4, 0x00, 0x99, 0x9e, 0x79, 0x69,
	0xf9, 0x60, 0xc5, 0xdc, 0x46, 0xbc, 0x7a, 0x40, 0xf7, 0xeb, 0xb9, 0x40, 0x05, 0x83, 0xe0, 0xd2,
	0x4a, 0x7c, 0x5c, 0x3c, 0xee, 0x40, 0x73, 0x40, 0x5e, 0x02, 0xf1, 0x93, 0xd8, 0xc0, 0xfe, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x84, 0x85, 0xd1, 0xf7, 0xfc, 0x00, 0x00, 0x00,
}
